 const knownTools = [
    "artisan's tools",
    "thieves' tools",
    "herbalism kit",
    "poisoner's kit",
    "disguise kit",
    "forgery kit",
    "navigator's tools",
    "alchemist's supplies",
    "brewer's supplies",
    "carpenter's tools",
    "cobbler's tools",
    "cook's utensils",
    "glassblower's tools",
    "jeweler's tools",
    "leatherworker's tools",
    "mason's tools",
    "painter's supplies",
    "potter's tools",
    "smith's tools",
    "tinker's tools",
    "weaver's tools",
    "woodcarver's tools",
    "gaming set",
    "musical instrument",
  ];