   const knownWeapons = [
    'battleaxe',
    'handaxe',
    'light hammer',
    'warhammer',
    'longsword',
    'shortsword',
    'shortbow',
    'longbow',
    'spear',
    'crossbow',
    'dagger',
    'rapier',
    'scimitar',
    'greataxe',
    'greatsword',
    'trident',
    'javelin',
    'quarterstaff',
    'simple weapons',
    'martial weapons',
    'hand crossbow',
    'light crossbow',
    'heavy crossbow',
    'war pick',
    'flail',
    'mace',
  ];
